server:
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tekbug/config-repo
          default-label: master
          clone-on-start: true
          force-pull: true