server:
  port: 8093
  shutdown: graceful
  netty:
    idle-timeout: 5s

spring:
  application:
    name: "user-service"
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 1500
        max-interval: 2500
        multiplier: 1.1
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

keycloak:
  serverUrl: http://localhost:8080
  realm: athenaRealm
  client-id: edge-service
  client-secret: akf3zJQ0sikPt0XqzMOKA37FsQQqMCJP

