package com.athena.v2.courses.enums;

public enum ActionType {
    LOGIN,
    LOGOUT,
    API_CALL,
    COURSE_REGISTRATION,
    COURSE_FETCH,
    COURSE_FETCH_ALL,
    COURSE_FETCH_BY_COURSE_NAME,
    COURSE_FETCH_ALL_BY_STATUS,
    COURSE_REINSTATE,
    COURSE_UPDATE,
    COURSE_DELETE,
    COURSE_BLOCK,
    PROFILE_UPDATE,
    DEFAULT_FLAG
}
