server:
  port: 8086
  shutdown: graceful
  netty:
    idle-timeout: 5s

spring:
  application:
    name: "teacher-service"
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 10
        initial-interval: 1500
        max-interval: 2500
        multiplier: 1.1

services.user.url: "http://localhost:8088"

logging:
  level:
    org.springframework.cloud.config.client: debug
    org.springdoc: debug