package com.athena.v2.enrollments.enums;

public enum ActionType {
    LOGIN,
    LOGOUT,
    API_CALL,
    ENROLLMENT_REGISTRATION,
    ENROLLMENT_FETCH,
    ENROLLMENT_FETCH_ALL,
    ENROLLMENT_FETCH_BY_COURSE_NAME,
    ENROLLMENT_FETCH_ALL_BY_STATUS,
    ENROLLMENT_REINSTATE,
    ENROLLMENT_UPDATE,
    ENROLLMENT_DELETE,
    ENROLLMENT_BLOCK,
    PROFILE_UPDATE,
    DEFAULT_FLAG
}
