server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: "discovery"

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF